# Generated by Django 3.0.2 on 2020-01-12 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost', models.IntegerField(verbose_name='cost')),
                ('others', models.CharField(max_length=800)),
                ('job', models.CharField(
                    choices=[(1, '法师'), (2, '猎人'), (3, '战士'), (4, '萨满祭司'), (5, '德鲁伊'), (6, '牧师'), (7, '潜行者'),
                             (8, '圣骑士'), (9, '术士'), (10, '污手党（猎人、战士、圣骑士）'), (11, '暗金教（法师、牧师、术士）'),
                             (12, '青莲帮（萨满祭司、德鲁伊、潜行者）'), (13, '中立'), (14, '衍生')], max_length=10)),
                ('amount', models.CharField(
                    choices=[(1, '基本（无色）'), (2, '普通（白色）'), (3, '稀有（蓝色)'), (4, '史诗（紫色）'), (5, '传说（橙色）'), (6, '衍生（无色）')],
                    max_length=30)),
                ('attact', models.IntegerField(verbose_name='attact')),
                ('times', models.IntegerField(verbose_name='times you can use')),
                ('pub_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hs.Version')),
            ],
        ),
        migrations.CreateModel(
            name='Minion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost', models.IntegerField(verbose_name='cost')),
                ('job', models.CharField(
                    choices=[(1, '法师'), (2, '猎人'), (3, '战士'), (4, '萨满祭司'), (5, '德鲁伊'), (6, '牧师'), (7, '潜行者'),
                             (8, '圣骑士'), (9, '术士'), (10, '污手党（猎人、战士、圣骑士）'), (11, '暗金教（法师、牧师、术士）'),
                             (12, '青莲帮（萨满祭司、德鲁伊、潜行者）'), (13, '中立'), (14, '衍生')], max_length=50)),
                ('amount', models.CharField(
                    choices=[(1, '基本（无色）'), (2, '普通（白色）'), (3, '稀有（蓝色)'), (4, '史诗（紫色）'), (5, '传说（橙色）'), (6, '衍生（无色）')],
                    max_length=30)),
                ('others', models.CharField(max_length=800)),
                ('attact', models.IntegerField(verbose_name='attact')),
                ('health', models.IntegerField(verbose_name='health')),
                ('pub_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hs.Version')),
            ],
        ),
        migrations.CreateModel(
            name='Magic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost', models.IntegerField(verbose_name='cost')),
                ('others', models.CharField(max_length=800)),
                ('job', models.CharField(
                    choices=[(1, '法师'), (2, '猎人'), (3, '战士'), (4, '萨满祭司'), (5, '德鲁伊'), (6, '牧师'), (7, '潜行者'),
                             (8, '圣骑士'), (9, '术士'), (10, '污手党（猎人、战士、圣骑士）'), (11, '暗金教（法师、牧师、术士）'),
                             (12, '青莲帮（萨满祭司、德鲁伊、潜行者）'), (13, '中立'), (14, '衍生')], max_length=10)),
                ('amount', models.CharField(
                    choices=[(1, '基本（无色）'), (2, '普通（白色）'), (3, '稀有（蓝色)'), (4, '史诗（紫色）'), (5, '传说（橙色）'), (6, '衍生（无色）')],
                    max_length=30)),
                ('pub_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hs.Version')),
            ],
        ),
        migrations.CreateModel(
            name='Dk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost', models.IntegerField(verbose_name='cost')),
                ('others', models.CharField(max_length=800)),
                ('job', models.CharField(
                    choices=[(1, '法师'), (2, '猎人'), (3, '战士'), (4, '萨满祭司'), (5, '德鲁伊'), (6, '牧师'), (7, '潜行者'),
                             (8, '圣骑士'), (9, '术士'), (10, '污手党（猎人、战士、圣骑士）'), (11, '暗金教（法师、牧师、术士）'),
                             (12, '青莲帮（萨满祭司、德鲁伊、潜行者）'), (13, '中立'), (14, '衍生')], max_length=10)),
                ('amount', models.CharField(
                    choices=[(1, '基本（无色）'), (2, '普通（白色）'), (3, '稀有（蓝色)'), (4, '史诗（紫色）'), (5, '传说（橙色）'), (6, '衍生（无色）')],
                    max_length=30)),
                ('ablity_name', models.CharField(max_length=50)),
                ('ablity_cost', models.IntegerField(verbose_name='ability cost')),
                ('ablity', models.CharField(max_length=400)),
                ('pub_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hs.Version')),
            ],
        ),
    ]
