# Generated by Django 3.0.2 on 2020-01-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('job', models.IntegerField(
                    choices=[(1, '法师'), (2, '猎人'), (3, '战士'), (4, '萨满祭司'), (5, '德鲁伊'), (6, '牧师'), (7, '潜行者'),
                             (8, '圣骑士'), (9, '术士'), (10, '污手党（猎人、战士、圣骑士）'), (11, '暗金教（法师、牧师、术士）'),
                             (12, '青莲帮（萨满祭司、德鲁伊、潜行者）'), (13, '中立'), (14, '衍生')])),
                ('effect', models.CharField(max_length=800)),
            ],
        ),
        migrations.AlterField(
            model_name='dk',
            name='rarity',
            field=models.IntegerField(choices=[(1, '基本'), (2, '普通'), (3, '稀有'), (4, '史诗'), (5, '传说'), (6, '衍生')]),
        ),
        migrations.AlterField(
            model_name='dk',
            name='skill_cost',
            field=models.IntegerField(null=True, verbose_name='技能费用（-1为被动英雄技能）'),
        ),
        migrations.AlterField(
            model_name='magic',
            name='rarity',
            field=models.IntegerField(choices=[(1, '基本'), (2, '普通'), (3, '稀有'), (4, '史诗'), (5, '传说'), (6, '衍生')]),
        ),
        migrations.AlterField(
            model_name='minion',
            name='rarity',
            field=models.IntegerField(choices=[(1, '基本'), (2, '普通'), (3, '稀有'), (4, '史诗'), (5, '传说'), (6, '衍生')]),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='rarity',
            field=models.IntegerField(choices=[(1, '基本'), (2, '普通'), (3, '稀有'), (4, '史诗'), (5, '传说'), (6, '衍生')]),
        ),
    ]
