# Generated by Django 3.0.2 on 2020-02-15 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('hs', '0002_auto_20200127_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='pub_version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hs.Version'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill',
            name='cost',
            field=models.IntegerField(verbose_name='技能费用（-1为被动英雄技能）'),
        ),
    ]
