# Generated by Django 3.0.2 on 2020-02-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hs', '0003_auto_20200215_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='ordering',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
