# Generated by Django 3.0.2 on 2020-07-25 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('hs', '0004_version_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='卡牌名称')),
                ('cost', models.IntegerField(verbose_name='卡牌费用')),
                ('job', models.IntegerField(
                    choices=[(1, '法师'), (2, '猎人'), (3, '战士'), (4, '萨满祭司'), (5, '德鲁伊'), (6, '牧师'), (7, '潜行者'),
                             (8, '圣骑士'), (9, '术士'), (10, '污手党（猎人、战士、圣骑士）'), (11, '暗金教（法师、牧师、术士）'),
                             (12, '青莲帮（萨满祭司、德鲁伊、潜行者）'), (13, '中立'), (14, '衍生'), (15, '恶魔猎手')], verbose_name='所属职业')),
                ('rarity',
                 models.IntegerField(choices=[(1, '基本'), (2, '普通'), (3, '稀有'), (4, '史诗'), (5, '传说'), (6, '衍生')],
                                     verbose_name='卡牌稀有度')),
                ('effect', models.CharField(max_length=800, verbose_name='卡牌效果')),
                ('explanation', models.CharField(max_length=800, null=True, verbose_name='卡牌背景描述')),
                ('armor', models.IntegerField(verbose_name='护甲值')),
                ('skill_name', models.CharField(max_length=50, verbose_name='英雄技能名称')),
                ('skill_cost', models.IntegerField(null=True, verbose_name='技能费用（-1为被动英雄技能）')),
                ('skill', models.CharField(max_length=400, verbose_name='英雄技能效果')),
                ('pub_version',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hs.Version', verbose_name='公布版本')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='卡牌名称')),
                ('cost', models.IntegerField(verbose_name='卡牌费用')),
                ('job', models.IntegerField(
                    choices=[(1, '法师'), (2, '猎人'), (3, '战士'), (4, '萨满祭司'), (5, '德鲁伊'), (6, '牧师'), (7, '潜行者'),
                             (8, '圣骑士'), (9, '术士'), (10, '污手党（猎人、战士、圣骑士）'), (11, '暗金教（法师、牧师、术士）'),
                             (12, '青莲帮（萨满祭司、德鲁伊、潜行者）'), (13, '中立'), (14, '衍生'), (15, '恶魔猎手')], verbose_name='所属职业')),
                ('rarity',
                 models.IntegerField(choices=[(1, '基本'), (2, '普通'), (3, '稀有'), (4, '史诗'), (5, '传说'), (6, '衍生')],
                                     verbose_name='卡牌稀有度')),
                ('effect', models.CharField(max_length=800, verbose_name='卡牌效果')),
                ('explanation', models.CharField(max_length=800, null=True, verbose_name='卡牌背景描述')),
                ('pub_version',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hs.Version', verbose_name='公布版本')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='magic',
            name='pub_version',
        ),
        migrations.AlterField(
            model_name='minion',
            name='attack',
            field=models.IntegerField(verbose_name='攻击力'),
        ),
        migrations.AlterField(
            model_name='minion',
            name='cost',
            field=models.IntegerField(verbose_name='卡牌费用'),
        ),
        migrations.AlterField(
            model_name='minion',
            name='effect',
            field=models.CharField(max_length=800, verbose_name='卡牌效果'),
        ),
        migrations.AlterField(
            model_name='minion',
            name='explanation',
            field=models.CharField(max_length=800, null=True, verbose_name='卡牌背景描述'),
        ),
        migrations.AlterField(
            model_name='minion',
            name='health',
            field=models.IntegerField(default=1, verbose_name='生命值'),
        ),
        migrations.AlterField(
            model_name='minion',
            name='job',
            field=models.IntegerField(
                choices=[(1, '法师'), (2, '猎人'), (3, '战士'), (4, '萨满祭司'), (5, '德鲁伊'), (6, '牧师'), (7, '潜行者'), (8, '圣骑士'),
                         (9, '术士'), (10, '污手党（猎人、战士、圣骑士）'), (11, '暗金教（法师、牧师、术士）'), (12, '青莲帮（萨满祭司、德鲁伊、潜行者）'),
                         (13, '中立'), (14, '衍生'), (15, '恶魔猎手')], verbose_name='所属职业'),
        ),
        migrations.AlterField(
            model_name='minion',
            name='name',
            field=models.CharField(max_length=50, verbose_name='卡牌名称'),
        ),
        migrations.AlterField(
            model_name='minion',
            name='pub_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hs.Version', verbose_name='公布版本'),
        ),
        migrations.AlterField(
            model_name='minion',
            name='rarity',
            field=models.IntegerField(choices=[(1, '基本'), (2, '普通'), (3, '稀有'), (4, '史诗'), (5, '传说'), (6, '衍生')],
                                      verbose_name='卡牌稀有度'),
        ),
        migrations.AlterField(
            model_name='minion',
            name='type',
            field=models.IntegerField(
                choices=[(1, '无'), (2, '野兽'), (3, '恶魔'), (4, '元素'), (5, '龙'), (6, '鱼人'), (7, '机械'), (8, '海盗'),
                         (9, '图腾'), (10, '全部')], verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='effect',
            field=models.CharField(max_length=800, verbose_name='英雄技能效果'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='job',
            field=models.IntegerField(
                choices=[(1, '法师'), (2, '猎人'), (3, '战士'), (4, '萨满祭司'), (5, '德鲁伊'), (6, '牧师'), (7, '潜行者'), (8, '圣骑士'),
                         (9, '术士'), (10, '污手党（猎人、战士、圣骑士）'), (11, '暗金教（法师、牧师、术士）'), (12, '青莲帮（萨满祭司、德鲁伊、潜行者）'),
                         (13, '中立'), (14, '衍生'), (15, '恶魔猎手')], verbose_name='所属职业'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=50, verbose_name='英雄技能名称'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='pub_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hs.Version', verbose_name='公布版本'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='attack',
            field=models.IntegerField(verbose_name='攻击力'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='cost',
            field=models.IntegerField(verbose_name='卡牌费用'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='durability',
            field=models.IntegerField(default=1, verbose_name='耐久度'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='effect',
            field=models.CharField(max_length=800, verbose_name='卡牌效果'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='explanation',
            field=models.CharField(max_length=800, null=True, verbose_name='卡牌背景描述'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='job',
            field=models.IntegerField(
                choices=[(1, '法师'), (2, '猎人'), (3, '战士'), (4, '萨满祭司'), (5, '德鲁伊'), (6, '牧师'), (7, '潜行者'), (8, '圣骑士'),
                         (9, '术士'), (10, '污手党（猎人、战士、圣骑士）'), (11, '暗金教（法师、牧师、术士）'), (12, '青莲帮（萨满祭司、德鲁伊、潜行者）'),
                         (13, '中立'), (14, '衍生'), (15, '恶魔猎手')], verbose_name='所属职业'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='name',
            field=models.CharField(max_length=50, verbose_name='卡牌名称'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='pub_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hs.Version', verbose_name='公布版本'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='rarity',
            field=models.IntegerField(choices=[(1, '基本'), (2, '普通'), (3, '稀有'), (4, '史诗'), (5, '传说'), (6, '衍生')],
                                      verbose_name='卡牌稀有度'),
        ),
        migrations.DeleteModel(
            name='Dk',
        ),
        migrations.DeleteModel(
            name='Magic',
        ),
    ]
