# Generated by Django 3.0.2 on 2020-07-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hs', '0005_auto_20200725_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='hero',
            name='job',
            field=models.IntegerField(
                choices=[(1, '法师'), (2, '猎人'), (3, '战士'), (4, '萨满祭司'), (5, '德鲁伊'), (6, '牧师'), (7, '潜行者'), (8, '圣骑士'),
                         (9, '术士'), (11, '恶魔猎手'), (12, '中立'), (13, '衍生')], verbose_name='所属职业'),
        ),
        migrations.AlterField(
            model_name='minion',
            name='job',
            field=models.IntegerField(
                choices=[(1, '法师'), (2, '猎人'), (3, '战士'), (4, '萨满祭司'), (5, '德鲁伊'), (6, '牧师'), (7, '潜行者'), (8, '圣骑士'),
                         (9, '术士'), (11, '恶魔猎手'), (12, '中立'), (13, '衍生')], verbose_name='所属职业'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='job',
            field=models.IntegerField(
                choices=[(1, '法师'), (2, '猎人'), (3, '战士'), (4, '萨满祭司'), (5, '德鲁伊'), (6, '牧师'), (7, '潜行者'), (8, '圣骑士'),
                         (9, '术士'), (11, '恶魔猎手'), (12, '中立'), (13, '衍生')], verbose_name='所属职业'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='job',
            field=models.IntegerField(
                choices=[(1, '法师'), (2, '猎人'), (3, '战士'), (4, '萨满祭司'), (5, '德鲁伊'), (6, '牧师'), (7, '潜行者'), (8, '圣骑士'),
                         (9, '术士'), (11, '恶魔猎手'), (12, '中立'), (13, '衍生')], verbose_name='所属职业'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='job',
            field=models.IntegerField(
                choices=[(1, '法师'), (2, '猎人'), (3, '战士'), (4, '萨满祭司'), (5, '德鲁伊'), (6, '牧师'), (7, '潜行者'), (8, '圣骑士'),
                         (9, '术士'), (11, '恶魔猎手'), (12, '中立'), (13, '衍生')], verbose_name='所属职业'),
        ),
    ]
