# Generated by Django 3.0.2 on 2020-07-26 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('hs', '0006_auto_20200726_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hs.Job', verbose_name='所属职业'),
        ),
        migrations.AlterField(
            model_name='job',
            name='color',
            field=models.CharField(max_length=100, verbose_name='职业颜色'),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=100, verbose_name='职业名称'),
        ),
        migrations.AlterField(
            model_name='minion',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hs.Job', verbose_name='所属职业'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='job',
            field=models.IntegerField(
                choices=[(1, '法师'), (2, '猎人'), (3, '战士'), (4, '萨满祭司'), (5, '德鲁伊'), (6, '牧师'), (7, '潜行者'), (8, '圣骑士'),
                         (9, '术士'), (11, '恶魔猎手'), (12, '中立')], verbose_name='所属职业'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hs.Job', verbose_name='所属职业'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hs.Job', verbose_name='所属职业'),
        ),
    ]
