# Generated by Django 3.0.2 on 2020-07-26 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('hs', '0007_auto_20200726_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hs.Job', verbose_name='所属职业'),
        ),
    ]
