# Generated by Django 3.0.2 on 2020-07-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hs', '0008_auto_20200726_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='随从类型标签名称')),
            ],
        ),
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='稀有度级别')),
                ('color', models.CharField(max_length=100, verbose_name='稀有度宝石颜色')),
                ('has_dragon', models.BooleanField(verbose_name='有无龙标')),
            ],
        ),
        migrations.AlterField(
            model_name='version',
            name='name',
            field=models.CharField(max_length=100, verbose_name='版本名称'),
        ),
        migrations.AlterField(
            model_name='version',
            name='ordering',
            field=models.IntegerField(verbose_name='版本序号'),
        ),
        migrations.AlterField(
            model_name='version',
            name='pub_date',
            field=models.DateField(verbose_name='上线日期'),
        ),
    ]
