# Generated by Django 3.0.2 on 2020-07-27 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('hs', '0009_auto_20200727_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='rarity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hs.Rarity', verbose_name='卡牌稀有度'),
        ),
        migrations.AlterField(
            model_name='minion',
            name='rarity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hs.Rarity', verbose_name='卡牌稀有度'),
        ),
        migrations.AlterField(
            model_name='rarity',
            name='has_dragon',
            field=models.BooleanField(verbose_name='有龙标'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='rarity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hs.Rarity', verbose_name='卡牌稀有度'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='rarity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hs.Rarity', verbose_name='卡牌稀有度'),
        ),
    ]
