# Generated by Django 3.0.2 on 2020-07-27 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('hs', '0010_auto_20200727_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minion',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hs.MinionType',
                                    verbose_name='随从类型'),
        ),
    ]
