# Generated by Django 3.1 on 2020-08-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs', '0011_auto_20200727_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='job',
        ),
        migrations.AddField(
            model_name='hero',
            name='job',
            field=models.ManyToManyField(to='hs.Job', verbose_name='所属职业'),
        ),
        migrations.RemoveField(
            model_name='minion',
            name='job',
        ),
        migrations.AddField(
            model_name='minion',
            name='job',
            field=models.ManyToManyField(to='hs.Job', verbose_name='所属职业'),
        ),
        migrations.RemoveField(
            model_name='spell',
            name='job',
        ),
        migrations.AddField(
            model_name='spell',
            name='job',
            field=models.ManyToManyField(to='hs.Job', verbose_name='所属职业'),
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='job',
        ),
        migrations.AddField(
            model_name='weapon',
            name='job',
            field=models.ManyToManyField(to='hs.Job', verbose_name='所属职业'),
        ),
    ]
